TEXT = {
    "zh": {
        "app_title": "YouTube 簡易下載器",
        "url": "網址",
        "output_folder": "輸出資料夾",
        "output_folder_error": "無法建立輸出資料夾",
        "browse": "瀏覽",
        "mode": "下載類型",
        "mode_audio": "只下載音訊",
        "mode_video": "只下載影片",
        "mode_both": "下載音訊與影片",
        "language": "語言",
        "audio_format": "音訊格式",
        "video_format": "影片格式",
        "mp3_quality": "MP3 品質",
        "embed_audio_thumbnail": "嵌入縮圖作為 MP3 封面",
        "embed_audio_thumbnail_tooltip": "只支援 MP3。會將 YouTube 縮圖嵌入 MP3 作為封面圖。",
        "mp4_quality": "下載畫質上限",
        "video_processing": "影片處理模式",
        "video_processing_keep": "保留下載格式",
        "video_processing_prefer": "優先下載相容格式",
        "video_processing_transcode": "下載後轉檔",
        "video_processing_osu": "osu! 相容影片",
        "video_codec": "視訊編碼",
        "video_codec_copy": "保留原格式",
        "video_codec_h264": "H.264",
        "resolution": "轉檔輸出解析度",
        "resolution_original": "保持原始解析度",
        "resolution_custom": "自訂解析度",
        "fps": "幀率",
        "fps_original": "保持原始幀率",
        "quality": "轉檔品質",
        "quality_high": "高畫質",
        "quality_balanced": "平衡",
        "quality_small": "小檔案",
        "quality_custom": "自訂 CRF",
        "crf": "CRF",
        "transcode_speed": "轉檔速度",
        "speed_veryfast": "極快",
        "speed_fast": "快速",
        "speed_medium": "平衡",
        "speed_slow": "高壓縮",
        "video_audio": "轉檔後音訊",
        "video_audio_keep": "保留音訊",
        "video_audio_remove": "移除音訊",
        "keep_original": "保留原始下載檔案",
        "add_local_video": "加入本機影片轉檔",
        "local_clip_button": "本機影片裁剪...",
        "local_clip_title": "本機影片裁剪",
        "local_clip_source": "來源影片",
        "local_clip_choose_source": "選擇影片",
        "local_clip_media_info": "媒體資訊",
        "local_clip_output_folder": "裁剪輸出資料夾",
        "local_clip_choose_output": "選擇資料夾",
        "local_clip_start": "開始",
        "local_clip_end": "結束",
        "local_clip_duration": "片段長度",
        "local_clip_expected_output": "預期輸出",
        "local_clip_create": "建立裁剪",
        "local_clip_probe_in_progress": "正在讀取本機影片資訊...",
        "local_clip_select_source": "請選擇一個支援的本機影片。",
        "local_clip_duration_unavailable": "需要已知且大於 0 的影片長度才能建立裁剪。",
        "local_clip_error_end_required": "請輸入有效的結束時間。",
        "local_clip_error_end_after_start": "結束時間必須大於開始時間。",
        "local_clip_error_end_after_duration": "結束時間不可超過影片長度。",
        "local_clip_error_output": "請選擇有效的裁剪輸出資料夾。",
        "local_clip_error_input": "無法讀取來源影片。",
        "local_clip_error_permission": "輸出資料夾沒有寫入權限，或檔案正在被使用。",
        "local_clip_error_space": "磁碟空間不足。",
        "local_clip_error_encoder": "H.264 編碼器不可用。",
        "local_clip_error_ffmpeg": "本機影片裁剪失敗。",
        "local_clip_error_failed": "本機影片裁剪失敗。",
        "local_clip_cancelled": "本機影片裁剪已取消。",
        "local_clip_range_display": "剪輯範圍：{start} → {end}（片段長度：{duration}）",
        "video_output_hint": "MP4 是容器；最大相容性請用 H.264 MP4 / yuv420p。CRF 越低畫質越高、檔案越大。",
        "osu_preset_hint": "osu!: MP4 / H.264 / yuv420p / max 720p / CRF 20 / no audio / faststart",
        "folder_rule": "分類方式",
        "filename_rule": "檔名格式",
        "custom_template": "自訂檔名",
        "folder_none": "不分類",
        "folder_mode": "依下載模式",
        "folder_channel": "依頻道",
        "folder_date": "依日期",
        "folder_playlist": "依播放清單",
        "filename_title": "標題",
        "filename_channel_title": "頻道 - 標題",
        "filename_playlist_index_title": "播放清單序號 - 標題",
        "filename_upload_date_title": "上傳日期 - 標題",
        "filename_custom": "自訂",
        "basic_settings": "基本設定",
        "advanced_settings": "進階設定",
        "trim_section": "時間範圍（可選）",
        "trim_enabled": "只下載指定片段",
        "trim_start": "開始",
        "trim_end": "結束",
        "trim_duration": "片段長度",
        "trim_range_display": "裁剪範圍：{start} → {end}（片段長度：{duration}）",
        "trim_single_video_only": "時間範圍下載目前僅支援單一影片",
        "trim_error_end_required": "請輸入有效的結束時間",
        "trim_error_end_after_start": "結束時間必須大於開始時間",
        "trim_error_end_after_duration": "結束時間不可超過影片長度",
        "file_organization": "檔案整理",
        "download_behavior": "下載行為",
        "video_processing_section": "影片處理",
        "queue_settings_hint": "開始下載時，目前設定會套用到整個佇列。",
        "skip_downloaded_tooltip": "依下載歷史與目前輸出類型略過已完成項目；檔案同名碰撞會另行提示。",
        "retry_failed_tooltip": "使用目前設定重新嘗試失敗項目。",
        "notify": "下載完成時提示",
        "check_updates_automatically": "自動檢查更新",
        "update_available": "有新版本可用：目前版本 {current}，最新版本 {latest}。",
        "open_release_page": "前往下載頁",
        "dismiss_update": "關閉",
        "start": "開始",
        "cancel": "取消",
        "open_output": "開啟輸出資料夾",
        "clear_url": "清空網址",
        "clear_status": "清空狀態",
        "preview": "影片預覽",
        "results": "下載結果",
        "status": "狀態 / 錯誤訊息",
        "queue": "下載佇列",
        "add_queue": "加入佇列",
        "move_up": "上移",
        "move_down": "下移",
        "remove_queue": "移除",
        "clear_queue": "清空佇列",
        "retry_failed": "重試失敗項目",
        "auto_retry": "自動重試",
        "retry_none": "不重試",
        "retry_once": "重試 1 次",
        "retry_twice": "重試 2 次",
        "retry_thrice": "重試 3 次",
        "retry_failed_empty": "目前沒有失敗項目可以重試。",
        "retry_failed_started": "準備重試失敗項目：{count} 個。",
        "retry_attempt": "重試 {attempt}/{max}: {url}",
        "resume_downloads": "保留未完成檔案並嘗試續傳",
        "resume_enabled_status": "續傳已啟用：會保留 .part 暫存檔並盡量續傳；MP3 若已進入 FFmpeg 轉檔階段，可能需要重新處理。",
        "resume_disabled_status": "續傳已停用：如果同一檔案有未完成下載，下次會重新下載。",
        "queue_empty": "佇列是空的。",
        "queue_added": "已加入佇列：{count} 個項目。",
        "queue_no_pending": "目前模式沒有需要下載的新項目。",
        "queue_building": "正在建立下載佇列...",
        "queue_item_failed": "加入佇列失敗",
        "queue_status_waiting": "等待",
        "queue_status_downloading": "下載中",
        "queue_status_completed": "完成",
        "queue_status_failed": "失敗",
        "queue_status_skipped": "略過",
        "queue_status_canceled": "已取消",
        "history": "下載歷史",
        "open_file": "開啟檔案",
        "copy_path": "複製路徑",
        "show_folder": "在資料夾中顯示",
        "clear_history": "清空歷史",
        "no_preview": "尚無預覽",
        "no_thumbnail": "無縮圖",
        "title": "標題",
        "channel": "頻道",
        "duration": "長度",
        "unknown": "未知",
        "fetching_info": "正在讀取影片資訊...",
        "info_loaded": "影片資訊已載入。",
        "preview_error": "預覽錯誤",
        "missing_url_title": "缺少網址",
        "missing_url": "請輸入一個或多個 YouTube 影片網址，每行一個。",
        "cannot_read_title": "無法讀取影片",
        "output_folder_line": "輸出資料夾",
        "done": "完成。",
        "download_completed": "下載完成",
        "download_completed_msg": "下載已完成。",
        "output_file": "輸出檔案",
        "batch_preview": "批量模式：偵測到 {count} 個網址。預覽只會在單一網址時顯示。",
        "batch_item": "批量下載 {current}/{total}",
        "batch_done": "批量下載完成：成功 {success}，失敗 {failed}。",
        "batch_auto_number": "批量模式會自動加編號，避免覆蓋既有檔案。",
        "batch_item_failed": "下載失敗",
        "playlist_preview": "播放清單模式：將在開始下載後讀取並展開影片清單。",
        "fetching_playlist": "正在讀取播放清單：{url}",
        "playlist_loaded": "播放清單「{title}」已載入，共 {count} 部影片。",
        "playlist_empty": "播放清單沒有可下載的公開影片。",
        "skip_downloaded": "略過已下載過的影片",
        "skip_downloaded_status": "已略過下載紀錄中存在的影片：{url}",
        "playlist_skip_summary": "播放清單檢查完成：略過 {skipped} 個已下載項目。",
        "error": "錯誤",
        "cancelling": "正在取消...",
        "cancelled": "下載已取消。",
        "copied_path": "已複製路徑",
        "file_missing_title": "找不到檔案",
        "file_missing": "檔案不存在",
        "exists_title": "檔案已存在",
        "exists_intro": "以下輸出檔案已存在：",
        "exists_choose": "請選擇要怎麼處理。",
        "overwrite": "覆蓋",
        "skip": "跳過",
        "auto_number": "自動加編號",
        "skipped": "已跳過",
        "progress_waiting": "等待下載",
        "history_cleared": "歷史紀錄已清空。",
        "history_recovered_corrupt": "偵測到損毀的歷史紀錄，已備份至：{backup_path}",
        "history_read_error": "無法讀取歷史紀錄；為避免資料遺失，已停用歷史寫入。",
        "history_recovery_failed": "歷史紀錄損毀且無法安全備份；已停用歷史寫入。",
        "history_save_failed": "檔案處理已完成，但無法儲存歷史紀錄：{error}",
        "error_unavailable": "影片無法使用，可能是私人影片、已刪除或所在地區無法觀看。",
        "error_login": "這部影片似乎需要登入。第一版尚不支援登入或 Cookie。",
        "error_network": "網路連線失敗或逾時，請檢查網路後再試一次。",
        "error_limited": "YouTube 暫時限制請求，請稍候再試。",
        "error_unsupported": "不支援此網址。請貼上公開 YouTube 影片網址。",
        "error_ffmpeg": "FFmpeg 轉檔或合併失敗，請稍後重試或改用其他格式。",
        "error_webm": "無法輸出 WEBM：目前來源格式或 FFmpeg 合併流程不支援此影片。請改用 MP4 或 MKV。",
        "error_permission": "檔案權限不足，請確認輸出資料夾可以寫入，或改選其他資料夾。",
        "error_path": "檔名或路徑可能太長或無效，請改短輸出路徑後再試。",
        "local_video_error": "請選擇支援的影片檔：mp4, mkv, webm, mov, avi。",
    },
    "en": {
        "app_title": "YouTube Simple Downloader",
        "url": "URL(s)",
        "output_folder": "Output Folder",
        "output_folder_error": "Cannot create output folder",
        "browse": "Browse",
        "mode": "Download Type",
        "mode_audio": "Audio only",
        "mode_video": "Video only",
        "mode_both": "Audio and video",
        "language": "Language",
        "audio_format": "Audio Format",
        "video_format": "Video Format",
        "mp3_quality": "MP3 Quality",
        "embed_audio_thumbnail": "Embed thumbnail as MP3 cover art",
        "embed_audio_thumbnail_tooltip": "MP3 only. Embeds the YouTube thumbnail in the MP3 as cover art.",
        "mp4_quality": "Download Quality Limit",
        "video_processing": "Video Processing",
        "video_processing_keep": "Keep downloaded format",
        "video_processing_prefer": "Prefer compatible format",
        "video_processing_transcode": "Transcode after download",
        "video_processing_osu": "osu! compatible video",
        "video_codec": "Video Codec",
        "video_codec_copy": "Keep original",
        "video_codec_h264": "H.264",
        "resolution": "Transcode Output Resolution",
        "resolution_original": "Original resolution",
        "resolution_custom": "Custom resolution",
        "fps": "FPS",
        "fps_original": "Original FPS",
        "quality": "Transcode Quality",
        "quality_high": "High quality",
        "quality_balanced": "Balanced",
        "quality_small": "Small file",
        "quality_custom": "Custom CRF",
        "crf": "CRF",
        "transcode_speed": "Transcode Speed",
        "speed_veryfast": "Very Fast",
        "speed_fast": "Fast",
        "speed_medium": "Balanced",
        "speed_slow": "Smaller File",
        "video_audio": "Audio After Transcode",
        "video_audio_keep": "Keep audio",
        "video_audio_remove": "Remove audio",
        "keep_original": "Keep original downloaded file",
        "add_local_video": "Add Local Video",
        "local_clip_button": "Local Clip...",
        "local_clip_title": "Local Clip",
        "local_clip_source": "Source video",
        "local_clip_choose_source": "Choose video",
        "local_clip_media_info": "Media information",
        "local_clip_output_folder": "Clip output folder",
        "local_clip_choose_output": "Choose folder",
        "local_clip_start": "Start",
        "local_clip_end": "End",
        "local_clip_duration": "Clip duration",
        "local_clip_expected_output": "Expected output",
        "local_clip_create": "Create Clip",
        "local_clip_probe_in_progress": "Reading local video information...",
        "local_clip_select_source": "Choose one supported local video.",
        "local_clip_duration_unavailable": "A known, positive video duration is required to create a clip.",
        "local_clip_error_end_required": "Please enter a valid end time.",
        "local_clip_error_end_after_start": "End time must be greater than start time.",
        "local_clip_error_end_after_duration": "End time cannot exceed the video duration.",
        "local_clip_error_output": "Choose a valid clip output folder.",
        "local_clip_error_input": "The source video could not be read.",
        "local_clip_error_permission": "The output folder cannot be written, or the file is in use.",
        "local_clip_error_space": "There is not enough disk space.",
        "local_clip_error_encoder": "The H.264 encoder is unavailable.",
        "local_clip_error_ffmpeg": "Local Clip failed in FFmpeg.",
        "local_clip_error_failed": "Local Clip failed.",
        "local_clip_cancelled": "Local Clip was cancelled.",
        "local_clip_range_display": "Clip range: {start} → {end} (Duration: {duration})",
        "video_output_hint": "MP4 is a container. For maximum compatibility, use H.264 MP4 / yuv420p. Lower CRF means higher quality and larger files.",
        "osu_preset_hint": "osu!: MP4 / H.264 / yuv420p / max 720p / CRF 20 / no audio / faststart",
        "folder_rule": "Folder Rule",
        "filename_rule": "Filename Format",
        "custom_template": "Custom Filename",
        "folder_none": "No grouping",
        "folder_mode": "By download mode",
        "folder_channel": "By channel",
        "folder_date": "By date",
        "folder_playlist": "By playlist",
        "filename_title": "Title",
        "filename_channel_title": "Channel - Title",
        "filename_playlist_index_title": "Playlist number - Title",
        "filename_upload_date_title": "Upload date - Title",
        "filename_custom": "Custom",
        "basic_settings": "Basic Settings",
        "advanced_settings": "Advanced Settings",
        "trim_section": "Time Range (Optional)",
        "trim_enabled": "Download only the selected segment",
        "trim_start": "Start",
        "trim_end": "End",
        "trim_duration": "Segment duration",
        "trim_range_display": "Trim range: {start} → {end} (Duration: {duration})",
        "trim_single_video_only": "Time range downloads currently support a single video only",
        "trim_error_end_required": "Please enter a valid end time",
        "trim_error_end_after_start": "End time must be greater than start time",
        "trim_error_end_after_duration": "End time cannot exceed the video duration",
        "file_organization": "File Organization",
        "download_behavior": "Download Behavior",
        "video_processing_section": "Video Processing",
        "queue_settings_hint": "The current settings apply to the entire queue when downloading starts.",
        "skip_downloaded_tooltip": "Uses download history and the current output type to skip completed items; filename collisions are handled separately.",
        "retry_failed_tooltip": "Retry failed items using the current settings.",
        "notify": "Notify when complete",
        "check_updates_automatically": "Check for updates automatically",
        "update_available": "A new version is available: current {current}, latest {latest}.",
        "open_release_page": "Open Download Page",
        "dismiss_update": "Dismiss",
        "start": "Start",
        "cancel": "Cancel",
        "open_output": "Open Output Folder",
        "clear_url": "Clear URL",
        "clear_status": "Clear Status",
        "preview": "Video Preview",
        "results": "Download Results",
        "status": "Status / Errors",
        "queue": "Download Queue",
        "add_queue": "Add to Queue",
        "move_up": "Move Up",
        "move_down": "Move Down",
        "remove_queue": "Remove",
        "clear_queue": "Clear Queue",
        "retry_failed": "Retry Failed",
        "auto_retry": "Auto Retry",
        "retry_none": "Do not retry",
        "retry_once": "Retry 1 time",
        "retry_twice": "Retry 2 times",
        "retry_thrice": "Retry 3 times",
        "retry_failed_empty": "There are no failed items to retry.",
        "retry_failed_started": "Retrying {count} failed item(s).",
        "retry_attempt": "Retry {attempt}/{max}: {url}",
        "resume_downloads": "Keep unfinished files and try to resume",
        "resume_enabled_status": "Resume is enabled: .part files are kept and yt-dlp will resume when possible. MP3 post-processing may need to run again after interruption.",
        "resume_disabled_status": "Resume is disabled: unfinished downloads for the same output path will restart.",
        "queue_empty": "The queue is empty.",
        "queue_added": "Added {count} item(s) to the queue.",
        "queue_no_pending": "There are no new items to download for the current mode.",
        "queue_building": "Building download queue...",
        "queue_item_failed": "Failed to add to queue",
        "queue_status_waiting": "Waiting",
        "queue_status_downloading": "Downloading",
        "queue_status_completed": "Completed",
        "queue_status_failed": "Failed",
        "queue_status_skipped": "Skipped",
        "queue_status_canceled": "Canceled",
        "history": "Download History",
        "open_file": "Open File",
        "copy_path": "Copy Path",
        "show_folder": "Show in Folder",
        "clear_history": "Clear History",
        "no_preview": "No preview",
        "no_thumbnail": "No thumbnail",
        "title": "Title",
        "channel": "Channel",
        "duration": "Duration",
        "unknown": "Unknown",
        "fetching_info": "Fetching video info...",
        "info_loaded": "Video info loaded.",
        "preview_error": "Preview error",
        "missing_url_title": "Missing URL",
        "missing_url": "Please enter one or more YouTube video URLs, one per line.",
        "cannot_read_title": "Cannot read video",
        "output_folder_line": "Output folder",
        "done": "Done.",
        "download_completed": "Download completed",
        "download_completed_msg": "Download completed.",
        "output_file": "Output file",
        "batch_preview": "Batch mode: detected {count} URLs. Preview is shown only for a single URL.",
        "batch_item": "Batch download {current}/{total}",
        "batch_done": "Batch completed: {success} succeeded, {failed} failed.",
        "batch_auto_number": "Batch mode uses auto numbering to avoid overwriting existing files.",
        "batch_item_failed": "Download failed",
        "playlist_preview": "Playlist mode: videos will be loaded after starting the download.",
        "fetching_playlist": "Reading playlist: {url}",
        "playlist_loaded": "Playlist \"{title}\" loaded with {count} videos.",
        "playlist_empty": "Playlist does not contain downloadable public videos.",
        "skip_downloaded": "Skip previously downloaded videos",
        "skip_downloaded_status": "Skipped previously downloaded video: {url}",
        "playlist_skip_summary": "Playlist check completed: skipped {skipped} previously downloaded item(s).",
        "error": "Error",
        "cancelling": "Cancelling...",
        "cancelled": "Download cancelled.",
        "copied_path": "Copied path",
        "file_missing_title": "File Missing",
        "file_missing": "File does not exist",
        "exists_title": "File Already Exists",
        "exists_intro": "The following output file already exists:",
        "exists_choose": "Choose what to do.",
        "overwrite": "Overwrite",
        "skip": "Skip",
        "auto_number": "Auto Number",
        "skipped": "skipped",
        "progress_waiting": "Waiting",
        "history_cleared": "History cleared.",
        "history_recovered_corrupt": "Corrupt history was detected and backed up to: {backup_path}",
        "history_read_error": "History could not be read; writes are blocked to prevent data loss.",
        "history_recovery_failed": "History is corrupt and could not be backed up safely; writes are blocked.",
        "history_save_failed": "File processing completed, but history could not be saved: {error}",
        "error_unavailable": "Video is unavailable, private, deleted, or blocked in this region.",
        "error_login": "This video appears to require sign-in. Version 1 does not support login or cookies yet.",
        "error_network": "Network connection failed or timed out. Please check the connection and try again.",
        "error_limited": "YouTube is temporarily limiting requests. Please wait a bit and try again.",
        "error_unsupported": "Unsupported URL. Please paste public YouTube video URLs.",
        "error_ffmpeg": "FFmpeg conversion or merge failed. Please retry later or try another format.",
        "error_webm": "Cannot output WEBM: this source format or FFmpeg merge flow is not supported for this video. Please use MP4 or MKV.",
        "error_permission": "File permission was denied. Please check the output folder or choose another folder.",
        "error_path": "The filename or path may be too long or invalid. Please try a shorter output folder.",
        "local_video_error": "Please choose supported video files: mp4, mkv, webm, mov, avi.",
    },
}


MODE_TEXT_KEYS = {
    "mp3": "mode_audio",
    "mp4": "mode_video",
    "both": "mode_both",
}

LEGACY_MODE_VALUES = {
    "mp3": "mp3",
    "mp4": "mp4",
    "both": "both",
    "mp3 + mp4": "both",
    "只下載音訊": "mp3",
    "只下載影片": "mp4",
    "下載音訊與影片": "both",
    "audio only": "mp3",
    "video only": "mp4",
    "audio and video": "both",
}


def normalize_download_mode(value: object, default: str | None = "mp3") -> str | None:
    normalized = LEGACY_MODE_VALUES.get(str(value or "").strip().lower())
    return normalized if normalized is not None else default


def download_mode_text(mode: object, language: str) -> str:
    normalized = normalize_download_mode(mode, None)
    if normalized is None:
        return str(mode or "")
    return TEXT[language][MODE_TEXT_KEYS[normalized]]
